
baseURL = "https://nutspaws.com/"
languageCode = "en-us"
title = "NutsPaws"
theme = "ananke"

enableRobotsTXT = true
buildFuture = false

[pagination]
pagerSize = 10

[params]
  mainSections = ["posts"]
